---
- name: Ensure build dependencies are installed.
  apt: "pkg={{ item }} state=installed"
  with_items: nodepool_build_depends
  when: nodepool_install_method == 'git' or nodepool_install_method == 'pip'
