---
- name: Install nodepool using pip.
  pip:
    name: "{{ nodepool_pip_name }}"
  when: nodepool_pip_version is none

- name: Install nodepool using pip.
  pip:
    name: "{{ nodepool_pip_name }}"
    version: "{{ nodepool_pip_version }}"
  when: nodepool_pip_version is not none
