---
# NOTE(pabelanger): This needs to be here for now, since we need python-pip.
- name: Ensure EPEL is enabled.
  yum:
    pkg: epel-release
    state: installed
  when: nodepool_install_method == 'git' or nodepool_install_method == 'pip'

- name: Ensure build dependencies are installed.
  yum: "pkg={{ item }} state=installed"
  with_items: nodepool_build_depends
  when: nodepool_install_method == 'git' or nodepool_install_method == 'pip'
