---
- name: Create system user account.
  user:
    createhome: yes
    home: /var/lib/nodepool
    name: nodepool

- name: Create required directories.
  file:
    group: nodepool
    owner: nodepool
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nodepool
    - "{{ nodepool_config_images_dir }}"
    - /var/log/nodepool

- name: Template secure configuration file.
  template:
    dest: "{{ nodepool_template_secure_conf_dest }}"
    src: "{{ nodepool_template_secure_conf_src }}"
  notify: Restart nodepool

- name: Template yaml configuration file.
  template:
    dest: "{{ nodepool_template_nodepool_yaml_dest }}"
    src: "{{ nodepool_template_nodepool_yaml_src }}"
  notify: Restart nodepool

- name: Copy sudoers file into place.
  copy:
    dest: /etc/sudoers.d/nodepool
    group: root
    mode: 0440
    owner: root
    src: nodepool.sudoers
    validate: 'visudo -cf %s'

- name: Copy logging configuration file.
  copy:
    dest: "{{ nodepool_config_log_config }}"
    src: "{{ nodepool_file_logging_conf }}"
  notify: Restart nodepool
