# Copyright 2015 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
---
- name: Create required directories
  become: true
  file:
    group: "{{ nodepool_user_group }}"
    owner: "{{ nodepool_user_name }}"
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/nodepool
    - /etc/nodepool/ssl
    - /opt/nodepool/images
    - /opt/nodepool/tmp
    - /var/log/nodepool

- name: Install nodepool configuration
  become: true
  template:
    dest: "{{ nodepool_file_nodepool_yaml_dest }}"
    group: "{{ nodepool_file_nodepool_yaml_group }}"
    mode: "{{ nodepool_file_nodepool_yaml_mode }}"
    owner: "{{nodepool_file_nodepool_yaml_owner }}"
    src: "{{ nodepool_file_nodepool_yaml_src }}"
  register: nodepool_file_nodepool_yaml

- name: Install nodepool secure configuration
  become: true
  template:
    dest: "{{ nodepool_file_secure_conf_dest }}"
    group: "{{ nodepool_file_secure_conf_group }}"
    mode: "{{ nodepool_file_secure_conf_mode }}"
    owner: "{{nodepool_file_secure_conf_owner }}"
    src: "{{ nodepool_file_secure_conf_src }}"
  register: nodepool_file_secure_conf

- name: Install builder logging configuration file
  become: true
  template:
    dest: "{{ nodepool_file_builder_logging_conf_dest }}"
    group: "{{ nodepool_file_builder_logging_conf_group }}"
    mode: "{{ nodepool_file_builder_logging_conf_mode }}"
    owner: "{{nodepool_file_builder_logging_conf_owner }}"
    src: "{{ nodepool_file_builder_logging_conf_src }}"
  register: nodepool_file_builder_logging_conf
  when: nodepool_file_builder_logging_conf_manage

- name: Install launcher logging configuration file
  become: true
  template:
    dest: "{{ nodepool_file_launcher_logging_conf_dest }}"
    group: "{{ nodepool_file_launcher_logging_conf_group }}"
    mode: "{{ nodepool_file_launcher_logging_conf_mode }}"
    owner: "{{nodepool_file_launcher_logging_conf_owner }}"
    src: "{{ nodepool_file_launcher_logging_conf_src }}"
  register: nodepool_file_launcher_logging_conf
  when: nodepool_file_launcher_logging_conf_manage

- name: Install zookeeper tls cacert configuration
  become: true
  template:
    dest: "{{ nodepool_file_zookeeper_tls_cacert_dest }}"
    group: "{{ nodepool_file_zookeeper_tls_cacert_group }}"
    mode: "{{ nodepool_file_zookeeper_tls_cacert_mode }}"
    owner: "{{ nodepool_file_zookeeper_tls_cacert_owner }}"
    src: "{{ nodepool_file_zookeeper_tls_cacert_src }}"
  register: nodepool_file_zookeeper_tls_cacert

- name: Install nodepool zookeeper tls cert configuration
  become: true
  template:
    dest: "{{ nodepool_file_zookeeper_tls_cert_dest }}"
    group: "{{ nodepool_file_zookeeper_tls_cert_group }}"
    mode: "{{ nodepool_file_zookeeper_tls_cert_mode }}"
    owner: "{{ nodepool_file_zookeeper_tls_cert_owner }}"
    src: "{{ nodepool_file_zookeeper_tls_cert_src }}"
  register: nodepool_file_zookeeper_tls_cert

- name: Install zookeeper tls key configuration
  become: true
  template:
    dest: "{{ nodepool_file_zookeeper_tls_key_dest }}"
    group: "{{ nodepool_file_zookeeper_tls_key_group }}"
    mode: "{{ nodepool_file_zookeeper_tls_key_mode }}"
    owner: "{{ nodepool_file_zookeeper_tls_key_owner }}"
    src: "{{ nodepool_file_zookeeper_tls_key_src }}"
  register: nodepool_file_zookeeper_tls_key
