---
- name: Define nodepool_build_depends.
  set_fact:
    nodepool_build_depends: "{{ __nodepool_build_depends | list }}"
  when: nodepool_build_depends is not defined

- name: Define nodepool_depends.
  set_fact:
    nodepool_depends: "{{ __nodepool_depends | list }}"
  when: nodepool_depends is not defined

- include: install/debian.yaml
  when: ansible_os_family == 'Debian'

- include: install/git.yaml
  when: nodepool_install_method == 'git'

- include: install/pip.yaml
  when: nodepool_install_method == 'pip'

- name: Create nodepool directory.
  file:
    path: /etc/nodepool
    state: directory
