---
- name: Define nodepool_build_depends.
  set_fact:
    nodepool_build_depends: "{{ __nodepool_build_depends | list }}"
  when: nodepool_build_depends is not defined

- name: Define nodepool_depends.
  set_fact:
    nodepool_depends: "{{ __nodepool_depends | list }}"
  when: nodepool_depends is not defined

- include: install/debian.yaml
  when: ansible_os_family == 'Debian'

- name: Download nodepool using git.
  git:
    dest: "{{ nodepool_git_dest }}"
    repo: "{{ nodepool_git_uri }}"
    version: "{{ nodepool_git_version }}"
  when: nodepool_install_method == 'git'

- name: Install nodepool using pip.
  pip:
    name: "file://{{ nodepool_git_dest }}"
  when: nodepool_install_method == 'git'

- name: Install nodepool using pip.
  pip:
    name: nodepool
  when: nodepool_install_method == 'pip'

- name: Install nodepool using pip.
  pip:
    name: nodepool
  when: nodepool_install_method == 'pip' and nodepool_pip_version is none

- name: Install nodepool using pip.
  pip:
    name: nodepool
    version: "{{ nodepool_pip_version }}"
  when: nodepool_install_method == 'pip' and nodepool_pip_version is not none
